/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpenseIndexRouteImport } from './routes/expense/index'
import { Route as ExpenseYearRouteImport } from './routes/expense/$year'
import { Route as InsightsTrendLineYearRouteImport } from './routes/insights/trend-line/$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseIndexRoute = ExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseYearRoute = ExpenseYearRouteImport.update({
  id: '/expense/$year',
  path: '/expense/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsTrendLineYearRoute = InsightsTrendLineYearRouteImport.update({
  id: '/insights/trend-line/$year',
  path: '/insights/trend-line/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expense/$year': typeof ExpenseYearRoute
  '/expense/': typeof ExpenseIndexRoute
  '/insights/trend-line/$year': typeof InsightsTrendLineYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expense/$year': typeof ExpenseYearRoute
  '/expense': typeof ExpenseIndexRoute
  '/insights/trend-line/$year': typeof InsightsTrendLineYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expense/$year': typeof ExpenseYearRoute
  '/expense/': typeof ExpenseIndexRoute
  '/insights/trend-line/$year': typeof InsightsTrendLineYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/expense/$year' | '/expense/' | '/insights/trend-line/$year'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expense/$year' | '/expense' | '/insights/trend-line/$year'
  id:
    | '__root__'
    | '/'
    | '/expense/$year'
    | '/expense/'
    | '/insights/trend-line/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpenseYearRoute: typeof ExpenseYearRoute
  ExpenseIndexRoute: typeof ExpenseIndexRoute
  InsightsTrendLineYearRoute: typeof InsightsTrendLineYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/': {
      id: '/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof ExpenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$year': {
      id: '/expense/$year'
      path: '/expense/$year'
      fullPath: '/expense/$year'
      preLoaderRoute: typeof ExpenseYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/trend-line/$year': {
      id: '/insights/trend-line/$year'
      path: '/insights/trend-line/$year'
      fullPath: '/insights/trend-line/$year'
      preLoaderRoute: typeof InsightsTrendLineYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpenseYearRoute: ExpenseYearRoute,
  ExpenseIndexRoute: ExpenseIndexRoute,
  InsightsTrendLineYearRoute: InsightsTrendLineYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
