/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpenseIndexRouteImport } from './routes/expense/index'
import { Route as ExpenseYearRouteImport } from './routes/expense/$year'
import { Route as InsightsTrendLineYearRouteImport } from './routes/insights/trend-line/$year'
import { Route as InsightsMonthlySummaryYearRouteImport } from './routes/insights/monthly-summary/$year'
import { Route as InsightsCategoryBreakdownYearRouteImport } from './routes/insights/category-breakdown/$year'
import { Route as InsightsMonthlySummaryYearMonthIndexRouteImport } from './routes/insights/monthly-summary/$year/$month/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseIndexRoute = ExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseYearRoute = ExpenseYearRouteImport.update({
  id: '/expense/$year',
  path: '/expense/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsTrendLineYearRoute = InsightsTrendLineYearRouteImport.update({
  id: '/insights/trend-line/$year',
  path: '/insights/trend-line/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsMonthlySummaryYearRoute =
  InsightsMonthlySummaryYearRouteImport.update({
    id: '/insights/monthly-summary/$year',
    path: '/insights/monthly-summary/$year',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsCategoryBreakdownYearRoute =
  InsightsCategoryBreakdownYearRouteImport.update({
    id: '/insights/category-breakdown/$year',
    path: '/insights/category-breakdown/$year',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsMonthlySummaryYearMonthIndexRoute =
  InsightsMonthlySummaryYearMonthIndexRouteImport.update({
    id: '/$month/',
    path: '/$month/',
    getParentRoute: () => InsightsMonthlySummaryYearRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expense/$year': typeof ExpenseYearRoute
  '/expense/': typeof ExpenseIndexRoute
  '/insights/category-breakdown/$year': typeof InsightsCategoryBreakdownYearRoute
  '/insights/monthly-summary/$year': typeof InsightsMonthlySummaryYearRouteWithChildren
  '/insights/trend-line/$year': typeof InsightsTrendLineYearRoute
  '/insights/monthly-summary/$year/$month/': typeof InsightsMonthlySummaryYearMonthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expense/$year': typeof ExpenseYearRoute
  '/expense': typeof ExpenseIndexRoute
  '/insights/category-breakdown/$year': typeof InsightsCategoryBreakdownYearRoute
  '/insights/monthly-summary/$year': typeof InsightsMonthlySummaryYearRouteWithChildren
  '/insights/trend-line/$year': typeof InsightsTrendLineYearRoute
  '/insights/monthly-summary/$year/$month': typeof InsightsMonthlySummaryYearMonthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expense/$year': typeof ExpenseYearRoute
  '/expense/': typeof ExpenseIndexRoute
  '/insights/category-breakdown/$year': typeof InsightsCategoryBreakdownYearRoute
  '/insights/monthly-summary/$year': typeof InsightsMonthlySummaryYearRouteWithChildren
  '/insights/trend-line/$year': typeof InsightsTrendLineYearRoute
  '/insights/monthly-summary/$year/$month/': typeof InsightsMonthlySummaryYearMonthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expense/$year'
    | '/expense/'
    | '/insights/category-breakdown/$year'
    | '/insights/monthly-summary/$year'
    | '/insights/trend-line/$year'
    | '/insights/monthly-summary/$year/$month/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expense/$year'
    | '/expense'
    | '/insights/category-breakdown/$year'
    | '/insights/monthly-summary/$year'
    | '/insights/trend-line/$year'
    | '/insights/monthly-summary/$year/$month'
  id:
    | '__root__'
    | '/'
    | '/expense/$year'
    | '/expense/'
    | '/insights/category-breakdown/$year'
    | '/insights/monthly-summary/$year'
    | '/insights/trend-line/$year'
    | '/insights/monthly-summary/$year/$month/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpenseYearRoute: typeof ExpenseYearRoute
  ExpenseIndexRoute: typeof ExpenseIndexRoute
  InsightsCategoryBreakdownYearRoute: typeof InsightsCategoryBreakdownYearRoute
  InsightsMonthlySummaryYearRoute: typeof InsightsMonthlySummaryYearRouteWithChildren
  InsightsTrendLineYearRoute: typeof InsightsTrendLineYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/': {
      id: '/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof ExpenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$year': {
      id: '/expense/$year'
      path: '/expense/$year'
      fullPath: '/expense/$year'
      preLoaderRoute: typeof ExpenseYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/trend-line/$year': {
      id: '/insights/trend-line/$year'
      path: '/insights/trend-line/$year'
      fullPath: '/insights/trend-line/$year'
      preLoaderRoute: typeof InsightsTrendLineYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/monthly-summary/$year': {
      id: '/insights/monthly-summary/$year'
      path: '/insights/monthly-summary/$year'
      fullPath: '/insights/monthly-summary/$year'
      preLoaderRoute: typeof InsightsMonthlySummaryYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/category-breakdown/$year': {
      id: '/insights/category-breakdown/$year'
      path: '/insights/category-breakdown/$year'
      fullPath: '/insights/category-breakdown/$year'
      preLoaderRoute: typeof InsightsCategoryBreakdownYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/monthly-summary/$year/$month/': {
      id: '/insights/monthly-summary/$year/$month/'
      path: '/$month'
      fullPath: '/insights/monthly-summary/$year/$month/'
      preLoaderRoute: typeof InsightsMonthlySummaryYearMonthIndexRouteImport
      parentRoute: typeof InsightsMonthlySummaryYearRoute
    }
  }
}

interface InsightsMonthlySummaryYearRouteChildren {
  InsightsMonthlySummaryYearMonthIndexRoute: typeof InsightsMonthlySummaryYearMonthIndexRoute
}

const InsightsMonthlySummaryYearRouteChildren: InsightsMonthlySummaryYearRouteChildren =
  {
    InsightsMonthlySummaryYearMonthIndexRoute:
      InsightsMonthlySummaryYearMonthIndexRoute,
  }

const InsightsMonthlySummaryYearRouteWithChildren =
  InsightsMonthlySummaryYearRoute._addFileChildren(
    InsightsMonthlySummaryYearRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpenseYearRoute: ExpenseYearRoute,
  ExpenseIndexRoute: ExpenseIndexRoute,
  InsightsCategoryBreakdownYearRoute: InsightsCategoryBreakdownYearRoute,
  InsightsMonthlySummaryYearRoute: InsightsMonthlySummaryYearRouteWithChildren,
  InsightsTrendLineYearRoute: InsightsTrendLineYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
